### PR TITLE
Add a package.json file

### PR DESCRIPTION
**Pull request by isaacs**
I added a package.json file to this.  Also, I took the liberty of publishing it on the npm registry (after updating the submodules, so that `make test` works.)

Scott,

Do you have an npm account already?  I'll add you as an owner.

--i

### CODE REVIEW

**Comment by smtlaissezfaire** [comment]
Awesome.  I'm not sure if I do - I had some issues with installing npm (see your bug tracker).  I _may_ have registered an account months and months ago though - it would either be under scott@railsnewbie.com or smtlaissezfaire.

**Comment by isaacs** [comment]
Yep.  There you are: http://registry.npmjs.org/-/user/org.couchdb.user:smtlaissezfaire

I added you as an owner of the ndb package.  If you remember the password that you used, you can run `npm config edit` and delete the _authCrypt line (if it exists).  Then run `npm adduser` and enter smtlaissezfaire the appropriate data.

If you don't remember your password, lmk, and i'll delete the record so you can re-create it.

**Comment by smtlaissezfaire** [comment]
Neat.  Ok - merged in and I created a release: v0.2.2.

Thanks!

**Comment by isaacs** [comment]
Kewl.  You can bump the version in the npm repo and `npm publish` if you're feeling ambitious.  I believe you can configure https://github.com/bmeck/npm-github-service to auto-publish when you push a specific tag.

**Pull request closed without merging**
